data-dir: "data/"

trans-dir: 'exps/trans'
num_senones: 6112
device: 'cuda:0'

kaldi-models-path: "exps/kaldi/"
conf-path: "exps/kaldi/conf"
torch-models-path: "exps/kaldi/torch"
kaldi-chain-mdl-path: "exps/kaldi/exp/chain_cleaned/tdnn_1d_sp_1k6/final.mdl"
kaldi-chain-txt-path: "exps/kaldi/exp/chain_cleaned/tdnn_1d_sp_1k6/final.txt"
transition-model-path: "exps/kaldi/exp/chain_cleaned/tdnn_1d_sp_1k6/final.mdl"
tree-path: "exps/kaldi/exp/chain_cleaned/tdnn_1d_sp_1k6/tree"
kaldi-phones-path: "exps/kaldi/exp/chain_cleaned/tdnn_1d_sp_1k6/phones.txt"

disambig-path: "exps/kaldi/data/lang_test_tgsmall/phones/disambig.int"
word-boundary-path: "exps/kaldi/data/lang_test_tgsmall/phones/word_boundary.int"
lang-graph-path: "exps/kaldi/data/lang_test_tgsmall/L.fst"
words-path: "exps/kaldi/data/lang_test_tgsmall/words.txt"
phones-pure-path: "exps/kaldi/data/phones/phones-list.txt"
phone-to-pure-phone-path: "exps/kaldi/data/phones/phone-to-pure-phone.int"
lexicon-path: "resources/lexicon.txt"
acoustic-model-path: "exps/kaldi/torch/acoustic_model.pt"