align:
  num_replicas: 2
  max_concurrent_queries: 64
  health_check_period_s: 10
  health_check_timeout_s: 30
  graceful_shutdown_timeout_s: 20
  graceful_shutdown_wait_loop_s: 2
  ray_actor_options: 
    num_cpus: 0.2